version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mygarage_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mygarage
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mygarage_network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: mygarage_backend
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/mygarage
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - mygarage_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mygarage_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mygarage_network

  prisma_studio:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mygarage_prisma
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/mygarage
    ports:
      - "5555:5555"
    depends_on:
      - mysql
    networks:
      - mygarage_network

volumes:
  mysql_data:

networks:
  mygarage_network:
    driver: bridge
